### PR TITLE
Draft 5: handshake and protocols

### PR DESCRIPTION
**Pull request by r58Playz**
This branch adds a handshake packet and protocols packet so protocol extensions can be created. Please provide feedback, this is a draft.

### CODE REVIEW

**Comment by ading2210** [comment]
This increases the complexity of the protocol significantly without much benefit. Needing the client to reply also increases overall latency during the handshake. Also, every existing Wisp implementation would have to adapt.

**Comment by ading2210** [comment]
Wisp is already deployed in production by multiple services, so it's too late to many any breaking changes to the protocol.

**Comment by ProgrammerIn-wonderland** [comment]
I agree with @ading2210 personally, 
I still believe using the connect packet as the handshake using the stream ID is the best approach since wisp is now in several production proxies

**Comment by ProgrammerIn-wonderland** [comment]
It's both a bit too early yet a bit too late for a breaking change already

**Pull request closed without merging**
